### ISSUE TITLE
Interested in making `monad-persist` available on Stackage LTS/nightlies?

### ISSUE THREAD

**Issue by jship** [cjdev/monad-persist#3]
Thanks for the really nice package!!!

Are you interested in making this package available on Stackage LTS/nightlies?  If so, I would be glad to list myself as the dependency maintainer.

**Comment by docmoxie** [comment]
Sure! I'm something of a newbie to that process, can you point me in the right direction?

**Comment by jship** [comment]
There is a guide over in the Stackage rep: https://github.com/commercialhaskell/stackage/tree/afab1a1f104ed1b356909361bd0933995d295ae6#add-your-package

The general flow after making sure the package is buildable/testable from Hackage is adding the package under an author section in stackage's `build-constraints.yml` file then making a PR to the repo with that change.  Let me know if I can help with the process!
